# Generated by Django 2.2.1 on 2019-05-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a commerce description cfghvthctgkvytv tcgvjykhyub'),
            preserve_default=False,
        ),
    ]
